name: Pantyho
favicon: null
layout_spectrum: 0.9633143946994096
typography_spectrum: 0.6580762870144099
title: Home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.10487846960313618
  lightness: 0.5398378854151815
  saturation: 0.25949492724612355
  rhythmicContrast: 0.828961762599647
purpose: []
